// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf7Zv_pPlx2EIP4dS3GZJBkUmvqOu7qzk',
    appId: '1:385670725036:web:7a8970c3acdb7110e10e09',
    messagingSenderId: '385670725036',
    projectId: 'instagram-512f5',
    authDomain: 'instagram-512f5.firebaseapp.com',
    storageBucket: 'instagram-512f5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkmaMU9ekVocmveTWFIDnJHv-eCwwhmdk',
    appId: '1:385670725036:android:a49a9af52db07830e10e09',
    messagingSenderId: '385670725036',
    projectId: 'instagram-512f5',
    storageBucket: 'instagram-512f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCat8IscCVJk5unU8SCw6gKYkvMtAGsrls',
    appId: '1:385670725036:ios:1c6ad21137a2d586e10e09',
    messagingSenderId: '385670725036',
    projectId: 'instagram-512f5',
    storageBucket: 'instagram-512f5.appspot.com',
    iosClientId: '385670725036-q6pd818ff65260ebqqc3nuacrh3bgvct.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCat8IscCVJk5unU8SCw6gKYkvMtAGsrls',
    appId: '1:385670725036:ios:1c6ad21137a2d586e10e09',
    messagingSenderId: '385670725036',
    projectId: 'instagram-512f5',
    storageBucket: 'instagram-512f5.appspot.com',
    iosClientId: '385670725036-q6pd818ff65260ebqqc3nuacrh3bgvct.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagram',
  );
}
